
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABRE_PAREN DIVIDIR FECHA_PAREN ID MAIS MENOS NUMERO VEZESE : ABRE_PAREN MAIS E E FECHA_PAREN\n         | ABRE_PAREN MENOS E E FECHA_PAREN\n         | ABRE_PAREN VEZES E E FECHA_PAREN\n         | ABRE_PAREN DIVIDIR E E FECHA_PARENE : IDE : NUMERO'
    
_lr_action_items = {'ABRE_PAREN':([0,3,4,5,6,7,8,9,10,11,12,17,18,19,20,],[2,-5,-6,2,2,2,2,2,2,2,2,-1,-2,-3,-4,]),'ID':([0,3,4,5,6,7,8,9,10,11,12,17,18,19,20,],[3,-5,-6,3,3,3,3,3,3,3,3,-1,-2,-3,-4,]),'NUMERO':([0,3,4,5,6,7,8,9,10,11,12,17,18,19,20,],[4,-5,-6,4,4,4,4,4,4,4,4,-1,-2,-3,-4,]),'$end':([1,3,4,17,18,19,20,],[0,-5,-6,-1,-2,-3,-4,]),'MAIS':([2,],[5,]),'MENOS':([2,],[6,]),'VEZES':([2,],[7,]),'DIVIDIR':([2,],[8,]),'FECHA_PAREN':([3,4,13,14,15,16,17,18,19,20,],[-5,-6,17,18,19,20,-1,-2,-3,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'E':([0,5,6,7,8,9,10,11,12,],[1,9,10,11,12,13,14,15,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> E","S'",1,None,None,None),
  ('E -> ABRE_PAREN MAIS E E FECHA_PAREN','E',5,'p_E_binop','parser_lf.py',126),
  ('E -> ABRE_PAREN MENOS E E FECHA_PAREN','E',5,'p_E_binop','parser_lf.py',127),
  ('E -> ABRE_PAREN VEZES E E FECHA_PAREN','E',5,'p_E_binop','parser_lf.py',128),
  ('E -> ABRE_PAREN DIVIDIR E E FECHA_PAREN','E',5,'p_E_binop','parser_lf.py',129),
  ('E -> ID','E',1,'p_E_id','parser_lf.py',133),
  ('E -> NUMERO','E',1,'p_E_numero','parser_lf.py',137),
]
